create table if not exists public.devices (
  id bigint generated by default as identity primary key,
  device_id text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schedules (
  id text not null,
  device_id text not null references public.devices(device_id) on delete cascade,
  name text not null default '새 일정',
  target_time text not null default '09:00',
  buffer_minutes integer not null default 10,
  plan jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (id, device_id),
  constraint schedules_target_time_format check (target_time ~ '^\d{2}:\d{2}$'),
  constraint schedules_buffer_minutes_range check (buffer_minutes >= 0 and buffer_minutes <= 240)
);

create index if not exists devices_updated_at_idx on public.devices(updated_at desc);
create index if not exists schedules_device_id_created_at_idx on public.schedules(device_id, created_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists devices_set_updated_at on public.devices;
create trigger devices_set_updated_at
before update on public.devices
for each row execute function public.set_updated_at();

drop trigger if exists schedules_set_updated_at on public.schedules;
create trigger schedules_set_updated_at
before update on public.schedules
for each row execute function public.set_updated_at();

create or replace function public.touch_device_updated_at()
returns trigger
language plpgsql
as $$
begin
  update public.devices
  set updated_at = now()
  where device_id = coalesce(new.device_id, old.device_id);
  return coalesce(new, old);
end;
$$;

drop trigger if exists schedules_touch_device_after_insert on public.schedules;
create trigger schedules_touch_device_after_insert
after insert on public.schedules
for each row execute function public.touch_device_updated_at();

drop trigger if exists schedules_touch_device_after_update on public.schedules;
create trigger schedules_touch_device_after_update
after update on public.schedules
for each row execute function public.touch_device_updated_at();

drop trigger if exists schedules_touch_device_after_delete on public.schedules;
create trigger schedules_touch_device_after_delete
after delete on public.schedules
for each row execute function public.touch_device_updated_at();

alter table public.devices enable row level security;
alter table public.schedules enable row level security;
